site_name: TUEP - Base de Conocimiento
site_url: https://walternieto.github.io/tuep/

theme:
  name: material

markdown_extensions:
  - attr_list
markdown_extensions:
  - pymdownx.emoji

plugins:
  - search
  - awesome-pages

extra:
  404: /404/

nav:
  - Bienvenida: index.md
  - La Tecnicatura: carrera.md
  - Materias: 
      - La Enseñanza...:
          - Introducción: m/8302/index.md
          - Masschelein: m/8302/c02masschelein-r.md
          - Meirieu: m/8302/c02meirieu-ro.md 
          - Alliaud: m/8302/c03-alliaud-r.md
          - Feldman: m/8302/c03-feldman-r.md
          - Ferry: m/8302/c03-ferry-r.md
          - Barato: m/8302/c06-barato-r.md
          - 1er Bimestre: m/8302/c07-bimestre1-r.md
          - Parcial: m/8302/c07-parcial1.md 
          - Maggio, IA: m/8302/c09-maggio-ro.md
          - Monzani, EF: m/8302/c09-monzani-o.md
          - Nicastro: m/8302/c11-nicastro-r.md
          - Milenaar: m/8302/c13-milenaar-r.md
          - Pedagogía: m/8302/c13-situada-r.md
          - Final: m/8302/c14-final-a.md
      - Gestión...: 
          - Introducción: m/8309/index.md
          - Clase01: m/8309/clase-01.md
          - Clase02: m/8309/clase-02.md
      - Diseño...: 
          - Presentación: m/8306/index.md
          - Tema01: m/8306/tema-01.md
          - Tema02: m/8306/tema-02.md
      - Contextos...: m/8301/index.md
      - Normativas:
          - Res 115/10: m/res115-10.md

  - Reflexión: reflexion.md
  - Contacto: contacto.md
